name: tests

on:
  push:
    branches: [ main ]
    paths:
    - '**.py'
    - '.github/workflows/tests.yml'
  pull_request:
    branches: [ main ]
    paths:
    - '**.py'
    - '.github/workflows/tests.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python3 -m pip install '.[test]'
    - name: Lint with ruff
      run: |
        python -m pip install ruff
        python -m ruff check .
    - name: Test with unittest
      run: |
        python -m unittest
